-- =============================================
-- 게임(game) 전장 떡밥 일괄 등록
-- Supabase SQL Editor에서 실행하세요.
-- =============================================

-- topics 테이블이 없으면 생성
CREATE TABLE IF NOT EXISTS topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  battlefield VARCHAR(50) NOT NULL,
  topic_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_topics_battlefield ON topics(battlefield);

-- 게임(game) 떡밥 삽입
INSERT INTO topics (battlefield, topic_text) VALUES
('game','롤 브론즈는 게임 접어야 하나?'),
('game','과금러 vs 무과금러'),
('game','게임 중 욕설'),
('game','게임 중 정치 발언'),
('game','게임 중 여혐 남혐'),
('game','여자라고 봐주기'),
('game','남자라고 캐리 강요'),
('game','게임 중 팀원 부모 욕'),
('game','랭겜 트롤 신고'),
('game','게임 계정 공유'),
('game','여친보다 게임'),
('game','남친보다 게임'),
('game','게임 현질 100만원'),
('game','확률형 아이템'),
('game','피시방에서 담배'),
('game','게임 중 음성채팅'),
('game','듀오 랭크'),
('game','버스 태워주기'),
('game','대리 랭크'),
('game','게임 핵 사용'),
('game','게임 방송 후원'),
('game','게임 스트리머 논란'),
('game','여캐 선택하면 여미새?'),
('game','남캐 고집'),
('game','게임 스킨 자랑'),
('game','뉴비 무시'),
('game','고인물 텃세'),
('game','게임 현질 인증'),
('game','과금 유도 패치'),
('game','밸런스 붕괴'),
('game','운빨 게임'),
('game','게임 실력 인생 자부심'),
('game','게임으로 돈 벌기'),
('game','e스포츠는 스포츠인가?'),
('game','게임 대회 상금'),
('game','팀보이스 강요'),
('game','친구 게임 실력 무시'),
('game','게임에서 고백'),
('game','게임 커플'),
('game','게임 아이디 실명'),
('game','게임 계정 판매'),
('game','게임 접는다 선언'),
('game','게임 중 잠수'),
('game','게임 중 AFK'),
('game','게임 채팅 금지'),
('game','게임 닉네임 분쟁'),
('game','게임 내 성희롱'),
('game','게임에서 정치색'),
('game','게임 팬덤 싸움'),
('game','콘솔 vs PC'),
('game','모바일 게임 무시'),
('game','패키지 게임 가격'),
('game','DLC 장사'),
('game','게임 복돌'),
('game','게임 리뷰 조작'),
('game','게임 평점 테러'),
('game','게임 버그 악용'),
('game','게임 업데이트 지연'),
('game','게임 현질 자랑'),
('game','게임 실력 허세'),
('game','게임 클랜 정치'),
('game','게임 길드 분쟁'),
('game','게임 보이스톡 여자인 척'),
('game','게임 성별 밝히기'),
('game','게임 스토리 스킵'),
('game','게임 난이도 하향'),
('game','게임 난이도 상향'),
('game','게임 공략 컨닝'),
('game','게임 캐리충'),
('game','게임 정치질'),
('game','게임 밴 사유'),
('game','게임 계정 정지 억울'),
('game','게임 중 인터넷 탓'),
('game','게임 핑 핑계'),
('game','게임 장비빨'),
('game','게임 실력빨'),
('game','게임 현질 필수'),
('game','게임 중 욕 박제'),
('game','게임 스킨 과금'),
('game','게임 스토리 vs 플레이'),
('game','게임 여성 전용 길드'),
('game','게임 남성 전용 길드'),
('game','게임 커뮤니티 친목'),
('game','게임 랭크 자랑'),
('game','게임 하면서 통화'),
('game','게임 숙제'),
('game','게임 일일 퀘스트'),
('game','게임 중 욕 고소'),
('game','게임 채팅 검열'),
('game','게임 서버 차별'),
('game','게임 현질 후 후회'),
('game','게임 접속 시간 제한'),
('game','게임 중 화풀이'),
('game','게임에서 나이 밝히기'),
('game','게임에서 직업 밝히기'),
('game','게임 랭크 부심'),
('game','게임은 시간 낭비인가?');

-- 완료
SELECT '✅ 게임(game) 떡밥 ' || COUNT(*) || '개 등록 완료' AS result FROM topics WHERE battlefield = 'game';
