-- =============================================
-- 돈(money) 전장 떡밥 일괄 등록
-- Supabase SQL Editor에서 실행하세요.
-- =============================================

-- topics 테이블이 없으면 생성
CREATE TABLE IF NOT EXISTS topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  battlefield VARCHAR(50) NOT NULL,
  topic_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_topics_battlefield ON topics(battlefield);

-- 돈(money) 떡밥 삽입
INSERT INTO topics (battlefield, topic_text) VALUES
('money','월급 300 적은가?'),
('money','월급 500면 충분?'),
('money','연봉 1억 평범?'),
('money','빚내서 투자'),
('money','주식 몰빵'),
('money','코인 투자'),
('money','부동산 불패'),
('money','명품 소비'),
('money','카드 할부'),
('money','가난은 게으름?'),
('money','부자는 노력 결과?'),
('money','로또 구매'),
('money','월세는 버리는 돈?'),
('money','전세 사기'),
('money','재테크 필수?'),
('money','적금 vs 투자'),
('money','비트코인'),
('money','테슬라 몰빵'),
('money','월급 관리 부모에게'),
('money','용돈제'),
('money','결혼 자금 부모 지원'),
('money','부모 찬스'),
('money','학자금 대출'),
('money','카푸어'),
('money','영끌'),
('money','빚투'),
('money','소비 통제'),
('money','짠테크'),
('money','탕진잼'),
('money','중고 거래 사기'),
('money','돈 빌려주기'),
('money','친구에게 돈 빌림'),
('money','보증 서주기'),
('money','연봉 공개'),
('money','투잡'),
('money','N잡러'),
('money','유튜브 수익'),
('money','인플루언서 수입'),
('money','부업 추천'),
('money','주식 단타'),
('money','주식 장투'),
('money','코인 단타'),
('money','코인 장투'),
('money','적자 인생'),
('money','월 100 저축'),
('money','월 200 저축'),
('money','연봉 역전'),
('money','재산 공개'),
('money','부모 재산 기대'),
('money','유산 상속'),
('money','증여세'),
('money','탈세'),
('money','현금 결제'),
('money','신용카드 포인트'),
('money','체크카드 vs 신용카드'),
('money','명품 리셀'),
('money','한정판 리셀'),
('money','게임 현질'),
('money','과소비'),
('money','소확행'),
('money','부동산 갭투자'),
('money','전세 대출'),
('money','신용점수'),
('money','카드론'),
('money','대출 여러 개'),
('money','연봉 협상'),
('money','퇴직금 투자'),
('money','연금저축'),
('money','국민연금 불신'),
('money','노후 준비'),
('money','재무관리 배우기'),
('money','부자 친구'),
('money','돈 많은 연인'),
('money','돈 없는 연인'),
('money','결혼 자산 차이'),
('money','돈 때문에 이별'),
('money','돈 때문에 싸움'),
('money','사업 실패'),
('money','창업 도전'),
('money','가게 권리금'),
('money','자영업 힘듦'),
('money','프랜차이즈 창업'),
('money','주식 추천 믿기'),
('money','코인 리딩방'),
('money','투자 사기'),
('money','중고 명품'),
('money','카드값 연체'),
('money','돈 자랑'),
('money','돈 숨기기'),
('money','통장 쪼개기'),
('money','소비 인증'),
('money','연봉 속이기'),
('money','경제적 자유'),
('money','파이어족'),
('money','월급 루팡');

-- 완료
SELECT '✅ 돈(money) 떡밥 ' || COUNT(*) || '개 등록 완료' AS result FROM topics WHERE battlefield = 'money';
