-- =============================================
-- 연애(love) 전장 떡밥 일괄 등록
-- Supabase SQL Editor에서 실행하세요.
-- =============================================

-- topics 테이블이 없으면 생성
CREATE TABLE IF NOT EXISTS topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  battlefield VARCHAR(50) NOT NULL,
  topic_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_topics_battlefield ON topics(battlefield);

-- 연애(love) 떡밥 삽입
INSERT INTO topics (battlefield, topic_text) VALUES
('love','전 애인이랑 연락'),
('love','카톡 읽씹'),
('love','데이트 더치페이'),
('love','이성 친구 많은 연인'),
('love','연인 SNS 공개 범위'),
('love','커플 폰 비번 공유'),
('love','잠수 이별'),
('love','연애 중 헌팅'),
('love','연애 중 클럽'),
('love','전 애인 사진 보관'),
('love','연애 중 게임 과몰입'),
('love','연인 휴대폰 검사'),
('love','기념일 안 챙기기'),
('love','장거리 연애'),
('love','커플템 강요'),
('love','연애 중 동거'),
('love','연애 중 술자리'),
('love','연애 중 여사친 남사친'),
('love','사내 연애'),
('love','연인 가족 반대'),
('love','결혼 압박'),
('love','연애 중 통금'),
('love','연인 옷차림 간섭'),
('love','연애 중 비밀'),
('love','연애 중 빚'),
('love','연애 중 투자 실패'),
('love','연애 중 주식'),
('love','연애 중 취미 강요'),
('love','연애 중 다이어트 강요'),
('love','연애 중 운동 강요'),
('love','연애 중 친구 차단'),
('love','연애 중 SNS 좋아요'),
('love','연애 중 외모 평가'),
('love','연애 중 비교'),
('love','연애 중 프로필뮤직'),
('love','연애 중 헤어지자 장난'),
('love','연애 중 연락 빈도'),
('love','연애 중 위치 공유'),
('love','연애 중 돈 빌리기'),
('love','연애 중 집 비번 공유'),
('love','연애 중 부모님 소개'),
('love','연애 중 해외여행'),
('love','연애 중 생일 선물 금액'),
('love','연애 중 게임 여캐'),
('love','연애 중 커플 사진'),
('love','연애 중 비밀 계정'),
('love','연애 중 헌팅포차'),
('love','연애 중 회식'),
('love','연애 중 주말 약속'),
('love','연애 중 야근'),
('love','연애 중 자기계발'),
('love','연애 중 시험 준비'),
('love','연애 중 헌신'),
('love','연애 중 결혼 얘기'),
('love','연애 중 카톡 답장 속도'),
('love','연애 중 전화 거절'),
('love','연애 중 친구 모임'),
('love','연애 중 게임 방송'),
('love','연애 중 과거 얘기'),
('love','연애 중 질투'),
('love','연애 중 외모 변신'),
('love','연애 중 명품 소비'),
('love','연애 중 취업 준비'),
('love','연애 중 알바'),
('love','연애 중 카톡 프사'),
('love','연애 중 SNS 댓글'),
('love','연애 중 술버릇'),
('love','연애 중 여행 사진'),
('love','연애 중 헌팅 DM'),
('love','연애 중 비밀 친구'),
('love','연애 중 통장 공개'),
('love','연애 중 재산 공개'),
('love','연애 중 사치'),
('love','연애 중 다툼 공개'),
('love','연애 중 화해 선물'),
('love','연애 중 장난 과함'),
('love','연애 중 친구 험담'),
('love','연애 중 이별 통보 방식'),
('love','연애 중 잠수 연락'),
('love','연애 중 애정 표현 부족'),
('love','연애 중 과한 애정 표현'),
('love','연애 중 친구 우선'),
('love','연애 중 가족 우선'),
('love','연애 중 커플룩'),
('love','연애 중 SNS 차단'),
('love','연애 중 과거 연애 비교'),
('love','연애 중 여행 비용'),
('love','연애 중 차 소유'),
('love','연애 중 결혼관 차이'),
('love','연애 중 종교 차이'),
('love','연애 중 취미 차이'),
('love','연애 중 나이 차이'),
('love','연애 중 군대 문제'),
('love','연애 중 해외 취업'),
('love','연애 중 집안 반대'),
('love','연애 중 애교 강요'),
('love','연애 중 욕설');

-- 완료
SELECT '✅ 연애(love) 떡밥 ' || COUNT(*) || '개 등록 완료' AS result FROM topics WHERE battlefield = 'love';
