-- =============================================
-- 결혼(marriage) 전장 떡밥 일괄 등록
-- Supabase SQL Editor에서 실행하세요.
-- =============================================

-- topics 테이블이 없으면 생성
CREATE TABLE IF NOT EXISTS topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  battlefield VARCHAR(50) NOT NULL,
  topic_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_topics_battlefield ON topics(battlefield);

-- 결혼(marriage) 떡밥 삽입
INSERT INTO topics (battlefield, topic_text) VALUES
('marriage','시댁 명절은 의무인가?'),
('marriage','처가 우선 vs 시댁 우선'),
('marriage','맞벌이 집안일 분담'),
('marriage','육아는 엄마 역할?'),
('marriage','결혼 후 친구 관계'),
('marriage','결혼 후 이성 친구'),
('marriage','결혼 후 용돈제'),
('marriage','결혼 전 동거'),
('marriage','결혼 후 각방'),
('marriage','결혼 후 개인 시간'),
('marriage','결혼식 비용 분담'),
('marriage','신혼집 위치'),
('marriage','시부모님 용돈'),
('marriage','장모님 용돈'),
('marriage','결혼 후 통장 합치기'),
('marriage','결혼 후 통장 분리'),
('marriage','아이 계획 필수?'),
('marriage','딩크 부부'),
('marriage','결혼 후 커리어 포기'),
('marriage','배우자 연봉 차이'),
('marriage','결혼 후 SNS 공개'),
('marriage','결혼 후 술자리'),
('marriage','결혼 후 게임'),
('marriage','결혼 후 헌팅'),
('marriage','결혼 후 친구 여행'),
('marriage','결혼 후 이직'),
('marriage','결혼 후 창업'),
('marriage','결혼 후 전세 대출'),
('marriage','결혼 후 부모 동거'),
('marriage','장인 장모 모시기'),
('marriage','시부모 모시기'),
('marriage','결혼 후 반려동물'),
('marriage','결혼 후 취미 생활'),
('marriage','결혼 후 명품 소비'),
('marriage','결혼 후 보험 가입'),
('marriage','결혼 후 재산 공개'),
('marriage','결혼 후 위치 공유'),
('marriage','결혼 후 휴대폰 검사'),
('marriage','결혼 후 이혼 고민'),
('marriage','이혼은 실패인가?'),
('marriage','재혼 편견'),
('marriage','결혼 후 친구 우선'),
('marriage','결혼 후 가족 우선'),
('marriage','결혼 후 종교 문제'),
('marriage','결혼 후 정치 성향'),
('marriage','결혼 후 집안 대소사'),
('marriage','결혼 후 외모 관리'),
('marriage','결혼 후 다이어트 강요'),
('marriage','결혼 후 기념일'),
('marriage','결혼 후 애정 표현'),
('marriage','결혼 후 성생활'),
('marriage','결혼 후 별거'),
('marriage','결혼 후 해외 이민'),
('marriage','결혼 후 맞벌이 강요'),
('marriage','결혼 후 외벌이'),
('marriage','결혼 후 육아휴직'),
('marriage','결혼 후 경력 단절'),
('marriage','결혼 후 시댁 스트레스'),
('marriage','결혼 후 처가 스트레스'),
('marriage','결혼 후 차 소유'),
('marriage','결혼 후 빚 공개'),
('marriage','결혼 후 친구 차단'),
('marriage','결혼 후 SNS 비공개'),
('marriage','결혼 후 취미 금지'),
('marriage','결혼 후 밤늦게 귀가'),
('marriage','결혼 후 회식'),
('marriage','결혼 후 해외여행'),
('marriage','결혼 후 자산 관리'),
('marriage','결혼 후 보험 설계'),
('marriage','결혼 후 생활비 분담'),
('marriage','결혼 후 명절 선물'),
('marriage','결혼 후 집안 행사'),
('marriage','결혼 후 가사 외주'),
('marriage','결혼 후 주말 각자 약속'),
('marriage','결혼 후 비밀 계정'),
('marriage','결혼 후 사생활'),
('marriage','결혼 후 친구 험담'),
('marriage','결혼 후 야근'),
('marriage','결혼 후 자기계발'),
('marriage','결혼 후 운동'),
('marriage','결혼 후 술버릇'),
('marriage','결혼 후 전 애인 연락'),
('marriage','결혼 후 가족 모임 빈도'),
('marriage','결혼 후 이혼 비용'),
('marriage','결혼 후 양가 갈등'),
('marriage','결혼 후 아이 교육'),
('marriage','결혼 후 사교육'),
('marriage','결혼 후 집 구매'),
('marriage','결혼 후 전세 vs 월세'),
('marriage','결혼 후 부동산 투자'),
('marriage','결혼 후 사업 실패'),
('marriage','결혼 후 금전 비밀'),
('marriage','결혼 후 친구 우정'),
('marriage','결혼은 필수인가?'),
('marriage','비혼 선언'),
('marriage','황혼 이혼');

-- 완료
SELECT '✅ 결혼(marriage) 떡밥 ' || COUNT(*) || '개 등록 완료' AS result FROM topics WHERE battlefield = 'marriage';
