-- =============================================
-- 직장(work) 전장 떡밥 일괄 등록
-- Supabase SQL Editor에서 실행하세요.
-- (앱은 현재 lib/battlefields.ts에서 토픽을 읽습니다. 이 테이블은 추후 API 연동용으로 사용할 수 있습니다.)
-- =============================================

-- topics 테이블이 없으면 생성 (선택 사항)
CREATE TABLE IF NOT EXISTS topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  battlefield VARCHAR(50) NOT NULL,
  topic_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_topics_battlefield ON topics(battlefield);

-- 직장(work) 떡밥 삽입 (이미 있으면 스킵하려면 아래 주석 참고)
INSERT INTO topics (battlefield, topic_text) VALUES
('work','회식은 업무 시간인가?'),
('work','퇴근 10분 전 업무 지시'),
('work','연차 사유 말해야 하나?'),
('work','점심시간에 업무 톡'),
('work','야근은 열정인가 착취인가?'),
('work','신입이 선배한테 말 놓기'),
('work','회사 단톡방 주말 알림'),
('work','팀장이 카톡 안 읽씹'),
('work','성과급 차등 지급'),
('work','회사에서 정치 얘기'),
('work','출근 5분 지각'),
('work','재택근무 눈치'),
('work','회사에서 유튜브 보기'),
('work','상사한테 이모지 사용'),
('work','회식 불참 눈치'),
('work','신입이 칼퇴'),
('work','경력직 텃세'),
('work','회사에서 개인 전화'),
('work','복장 자유 어디까지'),
('work','상사 말투 지적'),
('work','회식 2차 강요'),
('work','부장님 꼰대 발언'),
('work','인턴에게 커피 심부름'),
('work','팀 프로젝트 숟가락 얹기'),
('work','회사에서 낮잠'),
('work','연봉 공개해야 하나'),
('work','성과 가로채기'),
('work','회사에서 연애'),
('work','사내 정치 참여'),
('work','상사에게 직언'),
('work','MZ식 보고서'),
('work','보고서에 이모지'),
('work','점심 혼밥'),
('work','출장은 휴가인가'),
('work','상사 부당지시'),
('work','회식 장소 불만'),
('work','조기퇴근 눈치'),
('work','근무 중 게임'),
('work','회사 험담'),
('work','재택 중 외출'),
('work','상사에게 반말'),
('work','연봉 협상 요구'),
('work','회사 복지 과장 광고'),
('work','회사에서 정치 성향'),
('work','직급 대신 이름'),
('work','퇴사 통보 2주 전'),
('work','회사에서 SNS'),
('work','성과 압박'),
('work','근무 중 카페 방문'),
('work','연봉 역전'),
('work','팀원 무임승차'),
('work','야근 수당 미지급'),
('work','직장 내 고백'),
('work','회식에서 술 강요'),
('work','출장비 정산'),
('work','업무 중 쇼핑'),
('work','회사에서 운동'),
('work','사내 커플 특혜'),
('work','퇴근 후 전화'),
('work','팀장 갑질'),
('work','회사에서 정치글'),
('work','업무 공유 안 함'),
('work','경력 뻥튀기'),
('work','신입 교육 방치'),
('work','상사에게 읽씹'),
('work','연봉 동결'),
('work','회식비 더치페이'),
('work','부하직원 공개 혼내기'),
('work','출근 복장 논란'),
('work','인사평가 공정성'),
('work','회사에서 종교 얘기'),
('work','칼퇴 문화'),
('work','재택근무 생산성'),
('work','성과급 몰빵'),
('work','팀장 교체 요구'),
('work','회사에서 틱톡'),
('work','업무 중 넷플릭스'),
('work','상사 뒷담화'),
('work','조직개편 불만'),
('work','회사에서 주식'),
('work','업무 몰아주기'),
('work','상사 술버릇'),
('work','사내 연애 금지'),
('work','야근 자발적 참여'),
('work','회사에서 흡연'),
('work','신입이 연봉 자랑'),
('work','부서 이동 거부'),
('work','팀플 지각'),
('work','업무 평가 불복'),
('work','회사에서 정치 단톡'),
('work','퇴사 후 험담'),
('work','상사에게 카톡 답장 늦게'),
('work','회사 선물 강매'),
('work','근무 중 운동화'),
('work','팀장에게 휴가 거절'),
('work','업무 중 개인 공부'),
('work','직급 호칭 거부');

-- 완료
SELECT '✅ 직장(work) 떡밥 ' || COUNT(*) || '개 등록 완료' AS result FROM topics WHERE battlefield = 'work';
